  <div id="dlg_guidePage" class="easyui-dialog" data-options="closable:false,title:'引导页图片',buttons:'#bt_dlg_guidePage'" style="width:550px;height:300px;padding:10px;overflow:hidden" closed="true" >
    <div style="overflow:hidden;width:42.5%;height:100%;display:inline-block;" id="">
    </div>
    <div style="width:55%;height:100%;margin-left:10px;display:inline-block;overflow:hidden" id="">
    </div>
    </div>
  </div>
  <div id="bt_dlg_guidePage">
    <a class="easyui-linkbutton" iconCls="icon-email" id="a_save">保存</a>
    <a class="easyui-linkbutton" iconCls="icon-no" onclick="javascript:$('#dlg_guidePage').dialog('close')">关闭</a>
  </div>