<!-- 第三方样式文件 -->
<link rel="stylesheet" type="text/css" href="../insdep/easyui.css">
<link rel="stylesheet" type="text/css" href="../insdep/easyuiplus.css"/>

<!--<link rel="stylesheet" type="text/css" href="../easyui/themes/icon.css">
<link rel="stylesheet" type="text/css" href="../easyui/demo/demo.css">-->

<!-- 基于EasyUI框架的insdep样式-->
<link rel="stylesheet" type="text/css" href="../insdep/insdep_tables.css"/>
<link rel="stylesheet" type="text/css" href="../insdep/iconfont/iconfont.css"/>
<link rel="stylesheet" type="text/css" href="../insdep/insdep_theme_default.css"/>
<script type="text/javascript" src="../easyui/jquery.min.js"></script>
<script type="text/javascript" src="../easyui/jquery.easyui.min.js"></script>
<script type="text/javascript" src="../easyui/locale/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="../easyui/jquery-easyui-datagridview/datagrid-detailview.js"></script>

<!-- 自定义样式文件 -->
<link rel="stylesheet" type="text/css" href="./css/admin.css">

<!-- 自定义脚本文件 -->
<script type="text/javascript" src="./js/option.js"></script>
<script type="text/javascript" src="./js/util.js"></script>	<!-- 工具 -->